name: 'install config tool'
runs:
  using: "composite"
  steps:
    - run: | 
        if (Get-Module -ListAvailable -Name Microsoft.Xrm.Data.PowerShell) {
          Write-Host "Microsoft.Xrm.Data.PowerShell module exists skipping install."
        }
        else {
          Write-Host "Microsoft.Xrm.Data.PowerShell module does not exist installing now."
          Install-Module `
            -Name Microsoft.Xrm.Tooling.CrmConnector.PowerShell `
            -Force
          Install-Module `
            -Name Microsoft.Xrm.Tooling.ConfigurationMigration `
            -RequiredVersion 1.0.0.61 `
            -Force
        }
      shell: PowerShell