on:
  push: 
    paths:
      - 'install/**'
      - '.github/workflows/test-install.yml' # trigger workflow that tests the install action
jobs: 
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 # prevents breaking change
      - uses: ./install # name of another repo
      - run: |
          Get-Help Export-CrmDataFile
        shell: powershell