on: push
jobs: 
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2 # prevents breaking change
      - uses: ./install # name of another repo
        with:
          who-to-greet: world